"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { User } from "firebase/auth";
import { get, onValue, push, ref, remove, set, update } from "firebase/database";
import { auth, db } from "@/lib/firebase";
import { createStarterServer } from "@/lib/seed";
import { QUICK_REACTIONS, fallbackChannels } from "@/lib/constants";
import { attachmentKind, compressImage, fileToDataUrl, fmtSize, fmtTime, initials } from "@/lib/format";
import { attachmentStoragePath, storageDownloadUrl, uploadAttachment } from "@/lib/storage";
import { fetchGithubRepo, fetchMusicCard, searchGifs } from "@/lib/api";
import VoiceRoom from "./VoiceRoom";
import type { Channel, ChatMessage, DMMessage, DMThread, MessageAttachmentMeta, Poll, Server, UserProfile } from "@/lib/types";

type Member={uid:string;profile:UserProfile|null;role:string};
type ThreadMessage={id:string;authorId:string;content:string;createdAt:number};
const mapOf=<T,>(v:unknown):Record<string,T>=>v&&typeof v==="object"?v as Record<string,T>:{};
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:Date.now();

export default function WorkspaceV2({user}:{user:User}){
  const [profile,setProfile]=useState<UserProfile|null>(null);
  const [servers,setServers]=useState<Server[]>([]),[serverId,setServerId]=useState(""),[channels,setChannels]=useState<Channel[]>(fallbackChannels),[channelId,setChannelId]=useState("general");
  const [members,setMembers]=useState<Member[]>([]),[messages,setMessages]=useState<ChatMessage[]>([]),[search,setSearch]=useState("");
  const [mode,setMode]=useState<"server"|"friends"|"dms"|"profile">("server"),[navOpen,setNavOpen]=useState(false),[memberPanel,setMemberPanel]=useState(false);
  const [draft,setDraft]=useState(""),[replyTo,setReplyTo]=useState<ChatMessage|null>(null),[editingId,setEditingId]=useState<string|null>(null),[editText,setEditText]=useState("");
  const [friends,setFriends]=useState<string[]>([]),[requests,setRequests]=useState<Record<string,{fromName?:string;createdAt:number}>>({}),[friendName,setFriendName]=useState("");
  const [dmThreads,setDmThreads]=useState<Array<DMThread&{id:string;otherUid:string;profile:UserProfile|null}>>([]),[selectedDm,setSelectedDm]=useState<string|null>(null),[dmMessages,setDmMessages]=useState<DMMessage[]>([]),[dmDraft,setDmDraft]=useState("");
  const [profileOpen,setProfileOpen]=useState(false),[createServerOpen,setCreateServerOpen]=useState(false),[serverName,setServerName]=useState(""),[createChannelOpen,setCreateChannelOpen]=useState(false),[newChannelName,setNewChannelName]=useState("");
  const [inviteOpen,setInviteOpen]=useState(false),[inviteCode,setInviteCode]=useState(""),[joinOpen,setJoinOpen]=useState(false),[joinCode,setJoinCode]=useState("");
  const [gifOpen,setGifOpen]=useState(false),[gifQuery,setGifQuery]=useState(""),[gifResults,setGifResults]=useState<string[]>([]),[pollOpen,setPollOpen]=useState(false),[pollQuestion,setPollQuestion]=useState(""),[pollOptions,setPollOptions]=useState(["",""]);
  const [threadId,setThreadId]=useState<string|null>(null),[threadParent,setThreadParent]=useState<ChatMessage|null>(null),[threadMessages,setThreadMessages]=useState<ThreadMessage[]>([]),[threadDraft,setThreadDraft]=useState("");
  const [reactionCounts,setReactionCounts]=useState<Record<string,Record<string,number>>>({});
  const [busy,setBusy]=useState(false),[toast,setToast]=useState("");
  const listRef=useRef<HTMLDivElement>(null);

  const displayName=profile?.displayName||user.displayName||user.email?.split("@")[0]||"User";
  const currentServer=servers.find(s=>s.id===serverId);
  const currentChannel=channels.find(c=>c.id===channelId)||channels[0];
  const myRole=members.find(m=>m.uid===user.uid)?.role||"member";
  const canManage=myRole==="owner"||myRole==="admin";
  const filtered=useMemo(()=>search.trim()?messages.filter(m=>`${m.authorName||""} ${m.content}`.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR"))):messages,[messages,search]);

  useEffect(()=>onValue(ref(db,`users/${user.uid}/public`),s=>setProfile(s.val() as UserProfile|null)),[user.uid]);
  useEffect(()=>onValue(ref(db,`users/${user.uid}/servers`),async snap=>{const ids=Object.keys(mapOf<boolean>(snap.val()));const next=(await Promise.all(ids.map(async id=>{const s=await get(ref(db,`servers/${id}`));return s.exists()?({...s.val(),id} as Server):null}))).filter(Boolean) as Server[];setServers(next);setServerId(cur=>next.some(s=>s.id===cur)?cur:next[0]?.id||"")}),[user.uid]);
  useEffect(()=>{if(!serverId){setChannels(fallbackChannels);setMembers([]);return;}const c=onValue(ref(db,`channels/${serverId}`),s=>{const n=Object.entries(mapOf<Channel>(s.val())).map(([id,v])=>({...v,id})).sort((a,b)=>(a.position||0)-(b.position||0));setChannels(n.length?n:fallbackChannels);setChannelId(cur=>n.some(x=>x.id===cur)?cur:n.find(x=>x.type!=="voice")?.id||"general")});const m=onValue(ref(db,`serverMembers/${serverId}`),s=>{const entries=Object.entries(mapOf<{role?:string}>(s.val()));Promise.all(entries.map(async([uid,v])=>{const p=await get(ref(db,`users/${uid}/public`));return{uid,role:v.role||"member",profile:p.exists()?p.val() as UserProfile:null}})).then(setMembers)});return()=>{c();m()}},[serverId]);
  useEffect(()=>{if(!serverId||!channelId||mode!=="server"||currentChannel?.type==="voice"){setMessages([]);return;}return onValue(ref(db,`messages/${serverId}/${channelId}`),s=>setMessages(Object.entries(mapOf<ChatMessage>(s.val())).map(([id,v])=>({...v,id,createdAt:num(v.createdAt)})).sort((a,b)=>a.createdAt-b.createdAt).slice(-500)))},[serverId,channelId,mode,currentChannel?.type]);
  useEffect(()=>{if(!serverId||!channelId||mode!=="server")return;return onValue(ref(db,`reactions/${serverId}/${channelId}`),s=>{const all=mapOf<Record<string,boolean>>(s.val()),out:Record<string,Record<string,number>>={};for(const [mid,emojiMap] of Object.entries(all)){out[mid]={};for(const [emoji,users] of Object.entries(emojiMap||{}))out[mid][emoji]=Object.keys(users||{}).length;}setReactionCounts(out)})},[serverId,channelId,mode]);
  useEffect(()=>{if(!user.uid)return;const f=onValue(ref(db,`users/${user.uid}/friends`),s=>setFriends(Object.keys(mapOf<boolean>(s.val()))));const r=onValue(ref(db,`friendRequests/${user.uid}/incoming`),s=>setRequests(mapOf(s.val())));return()=>{f();r()}},[user.uid]);
  useEffect(()=>{if(mode!=="dms")return;return onValue(ref(db,`users/${user.uid}/dmThreads`),s=>{const ids=Object.keys(mapOf<boolean>(s.val()));Promise.all(ids.map(async id=>{const t=await get(ref(db,`dmThreads/${id}`));if(!t.exists())return null;const thread=t.val() as DMThread;const other=Object.keys(thread.participants||{}).find(x=>x!==user.uid)||user.uid;const p=await get(ref(db,`users/${other}/public`));return{...thread,id,otherUid:other,profile:p.exists()?p.val() as UserProfile:null}})).then(x=>setDmThreads(x.filter(Boolean) as Array<DMThread&{id:string;otherUid:string;profile:UserProfile|null}>))})},[mode,user.uid]);
  useEffect(()=>{if(!selectedDm||mode!=="dms"){setDmMessages([]);return;}return onValue(ref(db,`dmMessages/${selectedDm}`),s=>setDmMessages(Object.entries(mapOf<DMMessage>(s.val())).map(([id,v])=>({...v,id,createdAt:num(v.createdAt)})).sort((a,b)=>a.createdAt-b.createdAt).slice(-500)))},[selectedDm,mode]);
  useEffect(()=>{if(!threadId){setThreadMessages([]);return;}return onValue(ref(db,`threadMessages/${threadId}`),s=>setThreadMessages(Object.entries(mapOf<ThreadMessage>(s.val())).map(([id,v])=>({...v,id,createdAt:num(v.createdAt)})).sort((a,b)=>a.createdAt-b.createdAt)))},[threadId]);
  useEffect(()=>{if(listRef.current)listRef.current.scrollTop=listRef.current.scrollHeight},[messages,dmMessages,threadMessages]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(t)},[toast]);

  async function sendMessage(e:React.FormEvent){e.preventDefault();const text=draft.trim();if(!text||!serverId||currentChannel?.type==="voice")return;setDraft("");try{
    if(text.startsWith("/github ")){const card=await fetchGithubRepo(text.slice(8));await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:"",createdAt:Date.now(),githubCard:card});}
    else if(text.startsWith("/music ")){const card=await fetchMusicCard(text.slice(7));await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:"",createdAt:Date.now(),musicCard:card});}
    else {await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:text,createdAt:Date.now(),replyTo:replyTo?{id:replyTo.id,authorName:replyTo.authorName,content:replyTo.content.slice(0,180)}:null});setReplyTo(null)}}catch{setDraft(text);setToast("Mesaj gönderilemedi")}}
  async function editMessage(id:string){const t=editText.trim();if(!t)return;await update(ref(db,`messages/${serverId}/${channelId}/${id}`),{content:t,editedAt:Date.now()});setEditingId(null)}
  async function deleteMessage(id:string){await remove(ref(db,`messages/${serverId}/${channelId}/${id}`))}
  async function toggleReaction(id:string,emoji:string){const r=ref(db,`reactions/${serverId}/${channelId}/${id}/${emoji}/${user.uid}`);(await get(r)).exists()?await remove(r):await set(r,true)}
  async function createServer(){const name=serverName.trim();if(!name)return;setBusy(true);try{const r=push(ref(db,"servers"));const id=r.key!;const now=Date.now();await set(r,{name,ownerId:user.uid,createdAt:now});await set(ref(db,`serverMembers/${id}/${user.uid}`),{role:"owner",joinedAt:now});await set(ref(db,`users/${user.uid}/servers/${id}`),true);await set(push(ref(db,`channels/${id}`)),{name:"genel",type:"text",position:0,topic:"Genel sohbet"});await set(push(ref(db,`channels/${id}`)),{name:"sesli",type:"voice",position:1});setServerId(id);setMode("server");setCreateServerOpen(false);setServerName("")}catch{setToast("Sunucu oluşturulamadı")}finally{setBusy(false)}}
  async function createChannel(){const name=newChannelName.trim();if(!name||!serverId||!canManage)return;await set(push(ref(db,`channels/${serverId}`)),{name:name.replace(/[^a-zA-Z0-9-_ğüşöçıİĞÜŞÖÇ ]/g,"").trim()||"kanal",type:"text",position:channels.length,topic:""});setCreateChannelOpen(false);setNewChannelName("")}
  async function addFriend(){const n=friendName.trim().toLowerCase();if(!n)return;const s=await get(ref(db,`usernameIndex/${n}`));if(!s.exists()){setToast("Kullanıcı bulunamadı");return}const uid=String(s.val());if(uid===user.uid){setToast("Kendini ekleyemezsin");return}if(friends.includes(uid)){setToast("Zaten arkadaşsınız");return}await set(ref(db,`friendRequests/${uid}/incoming/${user.uid}`),{fromName:displayName,createdAt:Date.now()});await set(ref(db,`friendRequests/${user.uid}/outgoing/${uid}`),Date.now());setFriendName("");setToast("İstek gönderildi")}
  async function acceptFriend(uid:string){await set(ref(db,`friends/${user.uid}/${uid}`),true);await set(ref(db,`friends/${uid}/${user.uid}`),true);await remove(ref(db,`friendRequests/${user.uid}/incoming/${uid}`));await remove(ref(db,`friendRequests/${uid}/outgoing/${user.uid}`))}
  async function startDM(uid:string){const existing=dmThreads.find(t=>t.otherUid===uid);if(existing){setSelectedDm(existing.id);setMode("dms");return;}const r=push(ref(db,"dmThreads"));const id=r.key!,participants={[user.uid]:true,[uid]:true};await set(r,{participants,createdAt:Date.now()});await set(ref(db,`users/${user.uid}/dmThreads/${id}`),true);await set(ref(db,`users/${uid}/dmThreads/${id}`),true);setSelectedDm(id);setMode("dms")}
  async function sendDM(e:React.FormEvent){e.preventDefault();const text=dmDraft.trim();if(!text||!selectedDm)return;setDmDraft("");try{await set(push(ref(db,`dmMessages/${selectedDm}`)),{authorId:user.uid,content:text,createdAt:Date.now()})}catch{setDmDraft(text);setToast("DM gönderilemedi")}}
  async function uploadFile(file:File){if(!serverId||currentChannel?.type==="voice")return;setBusy(true);try{const id=push(ref(db,`messages/${serverId}/${channelId}`)).key!;const data=file.type.startsWith("image/")?await fileToDataUrl(await compressImage(file)):await fileToDataUrl(file);const path=attachmentStoragePath(serverId,channelId,id,file.name);const token=await uploadAttachment(path,data,file.type||"application/octet-stream");const attachment:MessageAttachmentMeta={type:attachmentKind(file),name:file.name,size:file.size,storagePath:path,storageToken:token};await set(ref(db,`messages/${serverId}/${channelId}/${id}`),{serverId,channelId,authorId:user.uid,authorName:displayName,content:"",createdAt:Date.now(),attachment})}catch{setToast("Dosya yüklenemedi")}finally{setBusy(false)}}
  async function searchGifAction(){if(!gifQuery.trim())return;try{setGifResults(await searchGifs(gifQuery))}catch{setToast("GIF araması başarısız")}}
  async function sendGif(url:string){await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:url,createdAt:Date.now()});setGifOpen(false)}
  async function createPoll(){const q=pollQuestion.trim(),options=pollOptions.map((x,i)=>({id:`o${i+1}`,text:x.trim(),votes:0})).filter(x=>x.text);if(!q||options.length<2)return;const p=push(ref(db,`polls/${serverId}/${channelId}`));const poll:Poll={id:p.key!,question:q,options,totalVotes:0,createdBy:user.uid};await set(p,poll);await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:"",createdAt:Date.now(),poll});setPollOpen(false);setPollQuestion("");setPollOptions(["",""])}
  async function votePoll(pollId:string,optionId:string){await set(ref(db,`pollVotes/${pollId}/${user.uid}`),optionId)}
  async function openThread(m:ChatMessage){let id=m.threadId;if(!id){id=push(ref(db,"threadMeta")).key!;await set(ref(db,`threadMeta/${id}`),{serverId,channelId,parentMessageId:m.id,createdAt:Date.now()});await update(ref(db,`messages/${serverId}/${channelId}/${m.id}`),{threadId:id})}setThreadParent(m);setThreadId(id)}
  async function sendThread(){const text=threadDraft.trim();if(!text||!threadId)return;setThreadDraft("");await set(push(ref(db,`threadMessages/${threadId}`)),{authorId:user.uid,content:text,createdAt:Date.now()})}
  async function createInvite(){if(!serverId)return;const code=Math.random().toString(36).slice(2,9).toUpperCase();await set(ref(db,`invites/${code}`),{serverId,createdBy:user.uid,createdAt:Date.now(),uses:0});setInviteCode(code);setInviteOpen(true)}
  async function joinInvite(){const code=joinCode.trim().toUpperCase();if(!code)return;const s=await get(ref(db,`invites/${code}`));if(!s.exists()){setToast("Davet bulunamadı");return}const d=s.val() as {serverId:string};const server=await get(ref(db,`servers/${d.serverId}`));if(!server.exists()){setToast("Sunucu bulunamadı");return}await set(ref(db,`serverMembers/${d.serverId}/${user.uid}`),{role:"member",joinedAt:Date.now()});await set(ref(db,`users/${user.uid}/servers/${d.serverId}`),true);setServerId(d.serverId);setMode("server");setJoinOpen(false);setJoinCode("")}
  async function copyInvite(){try{await navigator.clipboard.writeText(inviteCode);setToast("Davet kodu kopyalandı")}catch{setToast(inviteCode)}}

  if(mode==="friends")return <AppFrame title="Arkadaşlar" {...{user,profile,displayName,servers,serverId,setServerId,channels,channelId,setChannelId,currentServer,navOpen,setNavOpen,mode,setMode,canManage,onCreateServer:()=>setCreateServerOpen(true),onCreateChannel:()=>setCreateChannelOpen(true),onCreateInvite:()=>void createInvite(),onJoinInvite:()=>setJoinOpen(true)}}><FriendsPage {...{friends,requests,friendName,setFriendName,onAdd:()=>void addFriend(),onAccept:(uid:string)=>void acceptFriend(uid),onDM:(uid:string)=>void startDM(uid)}}/></AppFrame>;
  if(mode==="dms")return <AppFrame title={dmThreads.find(t=>t.id===selectedDm)?.profile?.displayName||"Mesajlar"} {...{user,profile,displayName,servers,serverId,setServerId,channels,channelId,setChannelId,currentServer,navOpen,setNavOpen,mode,setMode,canManage,onCreateServer:()=>setCreateServerOpen(true),onCreateChannel:()=>setCreateChannelOpen(true),onCreateInvite:()=>void createInvite(),onJoinInvite:()=>setJoinOpen(true)}}><DMPage threads={dmThreads} selected={selectedDm} setSelected={setSelectedDm} messages={dmMessages} draft={dmDraft} setDraft={setDmDraft} onSend={sendDM} currentUid={user.uid}/></AppFrame>;
  if(mode==="profile")return <AppFrame title="Profil" {...{user,profile,displayName,servers,serverId,setServerId,channels,channelId,setChannelId,currentServer,navOpen,setNavOpen,mode,setMode,canManage,onCreateServer:()=>setCreateServerOpen(true),onCreateChannel:()=>setCreateChannelOpen(true),onCreateInvite:()=>void createInvite(),onJoinInvite:()=>setJoinOpen(true)}}><ProfilePage profile={profile} displayName={displayName} onEdit={()=>setProfileOpen(true)}/></AppFrame>;

  return <AppFrame title={currentChannel?.name||"genel"} subtitle={currentChannel?.topic} {...{user,profile,displayName,servers,serverId,setServerId,channels,channelId,setChannelId,currentServer,navOpen,setNavOpen,mode,setMode,canManage,onCreateServer:()=>setCreateServerOpen(true),onCreateChannel:()=>setCreateChannelOpen(true),onCreateInvite:()=>void createInvite(),onJoinInvite:()=>setJoinOpen(true)}}>
    {currentChannel?.type==="voice" ? <div className="v15-voice-page"><VoiceRoom room={`signaling/${channelId}`} serverId={serverId} user={user}/></div> : <>
      <div className="v15-channel-body"><div className="v15-chat-body" ref={listRef}><div className="v15-channel-intro"><span>#</span><h1>#{currentChannel?.name||"genel"}</h1><p>{currentChannel?.topic||"Bu kanalın başlangıcı."}</p></div>{filtered.map(m=><MessageRow key={m.id} message={m} mine={m.authorId===user.uid} reactionCounts={reactionCounts[m.id]||{}} editing={editingId===m.id} editText={editText} setEditText={setEditText} onEdit={()=>{setEditingId(m.id);setEditText(m.content)}} onSaveEdit={()=>void editMessage(m.id)} onCancelEdit={()=>setEditingId(null)} onDelete={()=>void deleteMessage(m.id)} onReply={()=>setReplyTo(m)} onReact={e=>void toggleReaction(m.id,e)} onThread={()=>void openThread(m)} onVote={votePoll}/>)}</div>{memberPanel&&<MemberPanel members={members}/>}</div>
      {replyTo&&<div className="v15-reply-bar"><span><b>{replyTo.authorName||"User"}</b> yanıtlanıyor</span><button onClick={()=>setReplyTo(null)}>×</button></div>}
      <Composer draft={draft} setDraft={setDraft} onSubmit={sendMessage} onFile={uploadFile} onGif={()=>setGifOpen(v=>!v)} onPoll={()=>setPollOpen(v=>!v)} disabled={busy}/>
      {gifOpen&&<div className="v15-float-panel"><div className="v15-inline"><input value={gifQuery} onChange={e=>setGifQuery(e.target.value)} placeholder="GIF ara"/><button onClick={()=>void searchGifAction()}>Ara</button></div><div className="v15-gif-grid">{gifResults.map(u=><button key={u} onClick={()=>void sendGif(u)}><img src={u} alt="GIF"/></button>)}</div></div>}
      {pollOpen&&<PollComposer question={pollQuestion} setQuestion={setPollQuestion} options={pollOptions} setOptions={setPollOptions} onClose={()=>setPollOpen(false)} onCreate={()=>void createPoll()}/>} 
      {threadId&&<ThreadPanel parent={threadParent} messages={threadMessages} draft={threadDraft} setDraft={setThreadDraft} onSend={()=>void sendThread()} onClose={()=>{setThreadId(null);setThreadParent(null)}} currentUid={user.uid}/>} 
    </>}
    {profileOpen&&<ProfileModal profile={profile} user={user} onClose={()=>setProfileOpen(false)} onSaved={p=>{setProfile(p);setProfileOpen(false)}}/>}
    {createServerOpen&&<CreateServerModal value={serverName} setValue={setServerName} busy={busy} onClose={()=>setCreateServerOpen(false)} onCreate={()=>void createServer()}/>} 
    {createChannelOpen&&<CreateChannelModal value={newChannelName} setValue={setNewChannelName} onClose={()=>setCreateChannelOpen(false)} onCreate={()=>void createChannel()}/>} 
    {inviteOpen&&<InviteModal code={inviteCode} onCopy={()=>void copyInvite()} onClose={()=>setInviteOpen(false)}/>} 
    {joinOpen&&<JoinInviteModal value={joinCode} setValue={setJoinCode} onClose={()=>setJoinOpen(false)} onJoin={()=>void joinInvite()}/>} 
    {busy&&<div className="v15-uploading">İşleniyor…</div>}{toast&&<div className="v15-toast">{toast}</div>}
  </AppFrame>;
}

function AppFrame(p:any){const {children,title,subtitle,user,profile,displayName,servers,serverId,setServerId,channels,channelId,setChannelId,currentServer,navOpen,setNavOpen,mode,setMode,canManage,onCreateServer,onCreateChannel,onCreateInvite,onJoinInvite}=p;return <main className="v15-shell"><SideNavigation {...{profile,displayName,servers,serverId,setServerId,channels,channelId,setChannelId,currentServer,navOpen,setNavOpen,mode,setMode,canManage,onCreateServer,onCreateChannel,onCreateInvite,onJoinInvite}}/><section className="v15-main"><Topbar title={title} subtitle={subtitle} onMenu={()=>setNavOpen(true)} right={mode==="server"&&<div className="v15-search"><input value={""} readOnly placeholder=""/></div>}/>{children}</section></main>}
function Topbar({title,subtitle,onMenu,right}:{title:string;subtitle?:string;onMenu:()=>void;right?:React.ReactNode}){return <header className="v15-topbar"><button className="v15-menu" onClick={onMenu}>☰</button><div className="v15-top-title"><b>{title}</b>{subtitle&&<span>{subtitle}</span>}</div><div className="v15-top-actions">{right}</div></header>}
function SideNavigation({profile,displayName,servers,serverId,setServerId,channels,channelId,setChannelId,currentServer,navOpen,setNavOpen,mode,setMode,canManage,onCreateServer,onCreateChannel,onCreateInvite,onJoinInvite}:{profile:UserProfile|null;displayName:string;servers:Server[];serverId:string;setServerId:(x:string)=>void;channels:Channel[];channelId:string;setChannelId:(x:string)=>void;currentServer?:Server;navOpen:boolean;setNavOpen:(x:boolean)=>void;mode:string;setMode:(x:any)=>void;canManage:boolean;onCreateServer:()=>void;onCreateChannel:()=>void;onCreateInvite:()=>void;onJoinInvite:()=>void}){return <><aside className={`v15-sidebar ${navOpen?"open":""}`}><div className="v15-side-brand"><span className="v15-logo">A</span><div><b>AKAYROOM</b><small>V1.5</small></div><button className="v15-close-mobile" onClick={()=>setNavOpen(false)}>×</button></div><div className="v15-server-list"><button className={`v15-server-chip home ${mode==="server"&&serverId===""?"active":""}`} onClick={()=>{setMode("server");setNavOpen(false)}}>⌂</button>{servers.map(s=><button key={s.id} className={`v15-server-chip ${s.id===serverId&&mode==="server"?"active":""}`} onClick={()=>{setServerId(s.id);setMode("server");setNavOpen(false)}}>{s.iconUrl?<img src={s.iconUrl} alt=""/>:initials(s.name)}</button>)}<button className="v15-server-chip add" onClick={onCreateServer}>＋</button></div><div className="v15-nav-main"><div className="v15-server-heading"><span>SERVER</span><b>{currentServer?.name||"AkayRoom"}</b></div><button className={`v15-nav-action ${mode==="friends"?"active":""}`} onClick={()=>{setMode("friends");setNavOpen(false)}}>◉ Arkadaşlar</button><button className={`v15-nav-action ${mode==="dms"?"active":""}`} onClick={()=>{setMode("dms");setNavOpen(false)}}>✉ Mesajlar</button><div className="v15-nav-label">KANALLAR {canManage&&<button className="v15-mini-add" onClick={onCreateChannel}>＋</button>}</div>{channels.map(c=><button key={c.id} className={`v15-channel-row ${c.id===channelId&&mode==="server"?"active":""}`} onClick={()=>{setChannelId(c.id);setMode("server");setNavOpen(false)}}><span>{c.type==="voice"?"◉":c.type==="announcement"?"◈":"#"}</span>{c.name}</button>)}<div className="v15-nav-label">DAVET</div><button className="v15-nav-action small" onClick={onCreateInvite}>＋ Davet oluştur</button><button className="v15-nav-action small" onClick={onJoinInvite}>⇢ Davetle katıl</button></div><button className={`v15-account ${mode==="profile"?"active":""}`} onClick={()=>{setMode("profile");setNavOpen(false)}}><div className="v15-avatar">{profile?.avatarUrl?<img src={profile.avatarUrl} alt=""/>:initials(displayName)}</div><div><b>{displayName}</b><span>online</span></div><span className="v15-more">⋯</span></button></aside>{navOpen&&<button className="v15-backdrop" onClick={()=>setNavOpen(false)} aria-label="Kapat"/>}</>}
function MessageRow({message,mine,reactionCounts,editing,editText,setEditText,onEdit,onSaveEdit,onCancelEdit,onDelete,onReply,onReact,onThread,onVote}:{message:ChatMessage;mine:boolean;reactionCounts:Record<string,number>;editing:boolean;editText:string;setEditText:(x:string)=>void;onEdit:()=>void;onSaveEdit:()=>void;onCancelEdit:()=>void;onDelete:()=>void;onReply:()=>void;onReact:(e:string)=>void;onThread:()=>void;onVote:(pollId:string,optionId:string)=>void}){const [menu,setMenu]=useState(false);return <article className={`v15-message ${mine?"mine":""}`}><div className="v15-avatar msg">{initials(message.authorName||"User")}</div><div className="v15-msg-main"><div className="v15-meta"><b>{message.authorName||"User"}</b><time>{fmtTime(message.createdAt)}</time>{message.editedAt&&<em>(düzenlendi)</em>}</div>{message.replyTo&&<div className="v15-quoted">↳ {message.replyTo.authorName}: {message.replyTo.content}</div>}{editing?<div className="v15-edit"><input value={editText} onChange={e=>setEditText(e.target.value)} autoFocus/><button onClick={onSaveEdit}>Kaydet</button><button onClick={onCancelEdit}>İptal</button></div>:message.content&&/^https?:\/\//.test(message.content)&&(/giphy|media/i.test(message.content))?<img className="v15-gif" src={message.content} alt="GIF"/>:<p>{message.content}</p>}{message.githubCard&&<GitHubCardView card={message.githubCard}/>} {message.musicCard&&<MusicCardView card={message.musicCard}/>} {message.attachment&&<AttachmentView attachment={message.attachment}/>} {message.poll&&<PollCard poll={message.poll} onVote={onVote}/>}<div className="v15-msg-actions"><button onClick={onReply}>↩</button>{QUICK_REACTIONS.map(e=><button key={e} onClick={()=>onReact(e)}>{e}{reactionCounts[e]?<sup>{reactionCounts[e]}</sup>:null}</button>)}<button onClick={onThread}>⧉</button>{mine&&<><button onClick={onEdit}>✎</button><button onClick={onDelete}>⌫</button></>}<button onClick={()=>setMenu(v=>!v)}>⋯</button>{menu&&<div className="v15-mini-pop"><button onClick={()=>{navigator.clipboard?.writeText(message.content||"");setMenu(false)}}>Kopyala</button></div>}</div></div></article>}
function AttachmentView({attachment}:{attachment:MessageAttachmentMeta}){const [src,setSrc]=useState("");const [error,setError]=useState(false);useEffect(()=>{if(attachment.storagePath&&attachment.storageToken)setSrc(storageDownloadUrl(attachment.storagePath,attachment.storageToken));},[attachment]);if(!src)return <div className="v15-attachment">{attachment.name} · {fmtSize(attachment.size)}</div>;if(error)return <a className="v15-file" href={src} download={attachment.name}>İndir · {attachment.name}</a>;if(attachment.type==="image")return <img className="v15-attachment-image" src={src} alt={attachment.name} onError={()=>setError(true)}/>;if(attachment.type==="video")return <video className="v15-attachment-media" src={src} controls onError={()=>setError(true)}/>;if(attachment.type==="audio")return <audio className="v15-attachment-audio" src={src} controls onError={()=>setError(true)}/>;return <a className="v15-file" href={src} download={attachment.name}>{attachment.name} · {fmtSize(attachment.size)}</a>}
function PollCard({poll,onVote}:{poll:Poll;onVote:(id:string,optionId:string)=>void}){const [votes,setVotes]=useState<Record<string,string>>({});useEffect(()=>onValue(ref(db,`pollVotes/${poll.id}`),s=>setVotes(mapOf(s.val()))),[poll.id]);const counts:Record<string,number>={};poll.options.forEach(o=>counts[o.id]=0);Object.values(votes).forEach(v=>{if(counts[String(v)]!==undefined)counts[String(v)]++});const total=Object.values(counts).reduce((a,b)=>a+b,0);return <div className="v15-poll"><b>{poll.question}</b>{poll.options.map(o=><button key={o.id} className={votes["__me__"]===o.id?"selected":""} onClick={()=>onVote(poll.id,o.id)}><span>{o.text}</span><small>{counts[o.id]} · {total?Math.round(counts[o.id]/total*100):0}%</small></button>)}</div>}
function GitHubCardView({card}:{card:NonNullable<ChatMessage["githubCard"]>}){return <a className="v15-link-card" href={card.htmlUrl} target="_blank" rel="noreferrer"><strong>GitHub · {card.fullName}</strong><span>{card.description||""}</span><small>★ {card.stars.toLocaleString("tr-TR")} · forks {card.forks.toLocaleString("tr-TR")} · {card.language||"repo"}</small></a>}
function MusicCardView({card}:{card:NonNullable<ChatMessage["musicCard"]>}){return <div className="v15-music-card"><img src={card.artworkUrl} alt=""/><div><b>{card.trackName}</b><span>{card.artistName}</span><small>{card.collectionName}</small>{card.previewUrl&&<audio src={card.previewUrl} controls preload="none"/>}</div></div>}
function Composer({draft,setDraft,onSubmit,onFile,onGif,onPoll,disabled}:{draft:string;setDraft:(x:string)=>void;onSubmit:(e:React.FormEvent)=>void;onFile:(f:File)=>void;onGif:()=>void;onPoll:()=>void;disabled:boolean}){const f=useRef<HTMLInputElement>(null);return <form className="v15-composer" onSubmit={onSubmit}><button type="button" className="v15-icon-button" onClick={()=>f.current?.click()}>＋</button><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Mesaj yaz…" disabled={disabled}/><button type="button" className="v15-chip-button" onClick={onGif}>GIF</button><button type="button" className="v15-chip-button" onClick={onPoll}>POLL</button><button type="submit" disabled={!draft.trim()||disabled}>➤</button><input ref={f} type="file" hidden accept="image/*,video/*,audio/*,.pdf,.zip,.txt,.doc,.docx,.json,.csv" onChange={e=>{const file=e.target.files?.[0];if(file)onFile(file);e.currentTarget.value=""}}/></form>}
function FriendsPage({friends,requests,friendName,setFriendName,onAdd,onAccept,onDM}:{friends:string[];requests:Record<string,{fromName?:string;createdAt:number}>;friendName:string;setFriendName:(x:string)=>void;onAdd:()=>void;onAccept:(uid:string)=>void;onDM:(uid:string)=>void}){return <div className="v15-page"><section className="v15-card"><h1>Arkadaşlar</h1><div className="v15-inline"><input value={friendName} onChange={e=>setFriendName(e.target.value)} placeholder="kullanıcı adı"/><button onClick={onAdd}>İstek gönder</button></div></section>{Object.keys(requests).length>0&&<section className="v15-card"><h2>Gelen istekler</h2>{Object.entries(requests).map(([uid,r])=><div className="v15-list-row" key={uid}><span>{r.fromName||uid.slice(0,8)}</span><button onClick={()=>onAccept(uid)}>Kabul et</button></div>)}</section>}<section className="v15-card"><h2>Arkadaşlarım</h2>{friends.length?friends.map(uid=><div className="v15-list-row" key={uid}><span>@{uid.slice(0,10)}</span><button onClick={()=>onDM(uid)}>Mesaj</button></div>):<p className="muted">Henüz arkadaşın yok.</p>}</section></div>}
function DMPage({threads,selected,setSelected,messages,draft,setDraft,onSend,currentUid}:{threads:Array<DMThread&{id:string;otherUid:string;profile:UserProfile|null}>;selected:string|null;setSelected:(x:string|null)=>void;messages:DMMessage[];draft:string;setDraft:(x:string)=>void;onSend:(e:React.FormEvent)=>void;currentUid:string}){const active=threads.find(t=>t.id===selected);return <div className="v15-dm-layout"><div className="v15-dm-list">{threads.length?threads.map(t=><button key={t.id} className={selected===t.id?"active":""} onClick={()=>setSelected(t.id)}><span className="v15-avatar">{t.profile?.avatarUrl?<img src={t.profile.avatarUrl} alt=""/>:initials(t.profile?.displayName||t.otherUid)}</span><span><b>{t.profile?.displayName||t.otherUid.slice(0,8)}</b><small>@{t.profile?.username||"user"}</small></span></button>):<p className="muted">Henüz DM yok.</p>}</div><div className="v15-dm-chat">{selected?<><div className="v15-chat-body">{messages.map(m=><div className="v15-message" key={m.id}><div className="v15-avatar msg">{initials(m.authorId===currentUid?"Sen":active?.profile?.displayName||"User")}</div><div className="v15-msg-main"><div className="v15-meta"><b>{m.authorId===currentUid?"Sen":active?.profile?.displayName||"User"}</b><time>{fmtTime(m.createdAt)}</time></div><p>{m.content}</p></div></div>)}</div><form className="v15-composer" onSubmit={onSend}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Mesaj yaz…"/><button disabled={!draft.trim()}>➤</button></form></>:<div className="v15-empty-big">Bir konuşma seç.</div>}</div></div>}
function ProfilePage({profile,displayName,onEdit}:{profile:UserProfile|null;displayName:string;onEdit:()=>void}){return <div className="v15-page"><section className="v15-profile"><div className="v15-banner" style={{backgroundImage:profile?.bannerUrl?`url(${profile.bannerUrl})`:undefined,backgroundColor:profile?.bannerColor||"#171b27"}}/><div className="v15-profile-head"><div className="v15-big-avatar">{profile?.avatarUrl?<img src={profile.avatarUrl} alt=""/>:initials(displayName)}</div><div><h1>{displayName}</h1><p>@{profile?.username||"user"}</p>{profile?.title&&<span className="v15-pill">{profile.title}</span>}</div></div>{profile?.customStatus&&<div className="v15-status">{profile.customStatusEmoji} {profile.customStatus}</div>}{profile?.bio&&<p className="v15-bio">{profile.bio}</p>}</section><button className="v15-primary" onClick={onEdit}>Profili düzenle</button></div>}
function MemberPanel({members}:{members:Member[]}){return <aside className="v15-members"><span>ÜYELER · {members.length}</span>{members.map(m=><div className="v15-member" key={m.uid}><div className="v15-avatar">{m.profile?.avatarUrl?<img src={m.profile.avatarUrl} alt=""/>:initials(m.profile?.displayName||m.uid)}</div><div><b>{m.profile?.displayName||m.uid.slice(0,8)}</b><small>{m.role}</small></div></div>)}</aside>}
function ThreadPanel({parent,messages,draft,setDraft,onSend,onClose,currentUid}:{parent:ChatMessage|null;messages:ThreadMessage[];draft:string;setDraft:(x:string)=>void;onSend:()=>void;onClose:()=>void;currentUid:string}){return <div className="v15-thread-panel"><div className="v15-thread-head"><div><b>Yanıt dizisi</b><small>{parent?.authorName||"Mesaj"}</small></div><button onClick={onClose}>×</button></div><div className="v15-thread-body">{parent&&<div className="v15-thread-parent"><b>{parent.authorName}</b><p>{parent.content}</p></div>}{messages.map(m=><div className="v15-thread-message" key={m.id}><b>{m.authorId===currentUid?"Sen":m.authorId.slice(0,8)}</b><p>{m.content}</p><time>{fmtTime(m.createdAt)}</time></div>)}</div><form className="v15-thread-composer" onSubmit={e=>{e.preventDefault();onSend()}}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Yanıta yaz…"/><button disabled={!draft.trim()}>➤</button></form></div>}
function PollComposer({question,setQuestion,options,setOptions,onClose,onCreate}:{question:string;setQuestion:(x:string)=>void;options:string[];setOptions:(x:string[])=>void;onClose:()=>void;onCreate:()=>void}){return <div className="v15-float-panel"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Anket sorusu"/>{options.map((o,i)=><input key={i} value={o} onChange={e=>setOptions(options.map((x,j)=>j===i?e.target.value:x))} placeholder={`Seçenek ${i+1}`}/>)}<div className="v15-inline"><button type="button" onClick={()=>setOptions([...options,""])}>＋</button><button type="button" onClick={onClose}>İptal</button><button type="button" className="v15-primary" onClick={onCreate}>Oluştur</button></div></div>}
function CreateServerModal({value,setValue,busy,onClose,onCreate}:{value:string;setValue:(x:string)=>void;busy:boolean;onClose:()=>void;onCreate:()=>void}){return <Modal title="Yeni sunucu" onClose={onClose}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Sunucu adı" autoFocus/><div className="v15-modal-actions"><button onClick={onClose}>İptal</button><button className="v15-primary" disabled={!value.trim()||busy} onClick={onCreate}>Oluştur</button></div></Modal>}
function CreateChannelModal({value,setValue,onClose,onCreate}:{value:string;setValue:(x:string)=>void;onClose:()=>void;onCreate:()=>void}){return <Modal title="Yeni kanal" onClose={onClose}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="kanal adı" autoFocus/><div className="v15-modal-actions"><button onClick={onClose}>İptal</button><button className="v15-primary" disabled={!value.trim()} onClick={onCreate}>Oluştur</button></div></Modal>}
function InviteModal({code,onCopy,onClose}:{code:string;onCopy:()=>void;onClose:()=>void}){return <Modal title="Sunucu daveti" onClose={onClose}><div className="v15-invite-code">{code}</div><div className="v15-modal-actions"><button onClick={onCopy}>Kopyala</button><button className="v15-primary" onClick={onClose}>Tamam</button></div></Modal>}
function JoinInviteModal({value,setValue,onClose,onJoin}:{value:string;setValue:(x:string)=>void;onClose:()=>void;onJoin:()=>void}){return <Modal title="Davetle katıl" onClose={onClose}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="DAVETKODU" autoFocus/><div className="v15-modal-actions"><button onClick={onClose}>İptal</button><button className="v15-primary" disabled={!value.trim()} onClick={onJoin}>Katıl</button></div></Modal>}
function ProfileModal({profile,user,onClose,onSaved}:{profile:UserProfile|null;user:User;onClose:()=>void;onSaved:(p:UserProfile)=>void}){const [name,setName]=useState(profile?.displayName||"");const [bio,setBio]=useState(profile?.bio||"");const [status,setStatus]=useState(profile?.customStatus||"");return <Modal title="Profil ayarları" onClose={onClose}><label>GÖRÜNEN AD<input value={name} onChange={e=>setName(e.target.value)}/></label><label>BIO<textarea value={bio} onChange={e=>setBio(e.target.value)} rows={4}/></label><label>DURUM<input value={status} onChange={e=>setStatus(e.target.value)}/></label><div className="v15-modal-actions"><button onClick={onClose}>İptal</button><button className="v15-primary" onClick={async()=>{const next={...(profile||{}),username:profile?.username||user.email?.split("@")[0]||"user",usernameLower:profile?.usernameLower||user.email?.split("@")[0]?.toLowerCase()||"user",displayName:name.trim()||"User",bio,customStatus:status,createdAt:profile?.createdAt||Date.now()};await update(ref(db,`users/${user.uid}/public`),next);onSaved(next as UserProfile)}}>Kaydet</button></div></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="v15-modal-wrap"><div className="v15-modal"><div className="v15-modal-head"><b>{title}</b><button onClick={onClose}>×</button></div>{children}</div></div>}
