"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { User } from "firebase/auth";
import { get, onChildAdded, onValue, push, ref, remove, set, update } from "firebase/database";
import { auth, db } from "@/lib/firebase";
import { QUICK_REACTIONS, fallbackCats, fallbackChannels } from "@/lib/constants";
import { attachmentKind, compressImage, fileToDataUrl, fmtSize, fmtTime, initials } from "@/lib/format";
import { attachmentStoragePath, storageDownloadUrl, uploadAttachment } from "@/lib/storage";
import { fetchGithubRepo, fetchMusicCard, searchGifs } from "@/lib/api";
import VoiceRoom from "./VoiceRoom";
import type { Category, Channel, ChatMessage, DMMessage, DMThread, MessageAttachmentMeta, Poll, Server, UserProfile } from "@/lib/types";

const asMap = <T,>(value: unknown): Record<string,T> => value && typeof value === "object" ? value as Record<string,T> : {};
const timestamp = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? v : Date.now();
const byPosition = (a:{position?:number},b:{position?:number}) => (a.position ?? 0) - (b.position ?? 0);

type Member = { uid:string; profile:UserProfile|null; role:string };
type ThreadMessage = { id:string; authorId:string; content:string; createdAt:number };

export default function Workspace({user}:{user:User}){
  const [profile,setProfile]=useState<UserProfile|null>(null);
  const [servers,setServers]=useState<Server[]>([]),[serverId,setServerId]=useState(""),[channels,setChannels]=useState<Channel[]>(fallbackChannels),[channelId,setChannelId]=useState("general"),[categories,setCategories]=useState<Category[]>(fallbackCats);
  const [members,setMembers]=useState<Member[]>([]),[messages,setMessages]=useState<ChatMessage[]>([]),[search,setSearch]=useState("");
  const [draft,setDraft]=useState(""),[replyTo,setReplyTo]=useState<ChatMessage|null>(null),[editingId,setEditingId]=useState<string|null>(null),[editText,setEditText]=useState("");
  const [navOpen,setNavOpen]=useState(false),[memberPanel,setMemberPanel]=useState(false),[mode,setMode]=useState<"server"|"friends"|"dms"|"profile">("server");
  const [dmThreads,setDmThreads]=useState<Array<DMThread&{id:string;otherUid:string;profile:UserProfile|null}>>([]),[selectedDm,setSelectedDm]=useState<string|null>(null),[dmMessages,setDmMessages]=useState<DMMessage[]>([]),[dmDraft,setDmDraft]=useState("");
  const [friends,setFriends]=useState<string[]>([]),[requests,setRequests]=useState<Record<string,{fromName?:string;createdAt:number}>>({}),[friendName,setFriendName]=useState("");
  const [pendingFile,setPendingFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[toast,setToast]=useState("");
  const [gifOpen,setGifOpen]=useState(false),[gifQuery,setGifQuery]=useState(""),[gifResults,setGifResults]=useState<string[]>([]);
  const [pollOpen,setPollOpen]=useState(false),[pollQuestion,setPollQuestion]=useState(""),[pollOptions,setPollOptions]=useState(["",""]);
  const [createServerOpen,setCreateServerOpen]=useState(false),[serverName,setServerName]=useState("");
  const [createChannelOpen,setCreateChannelOpen]=useState(false),[newChannelName,setNewChannelName]=useState("");
  const [inviteCode,setInviteCode]=useState(""),[joinCode,setJoinCode]=useState(""),[inviteOpen,setInviteOpen]=useState(false),[joinOpen,setJoinOpen]=useState(false);
  const [profileOpen,setProfileOpen]=useState(false),[threadId,setThreadId]=useState<string|null>(null),[threadParent,setThreadParent]=useState<ChatMessage|null>(null),[threadMessages,setThreadMessages]=useState<ThreadMessage[]>([]),[threadDraft,setThreadDraft]=useState("");
  const [callChannel,setCallChannel]=useState<string|null>(null);
  const [reactionMap,setReactionMap]=useState<Record<string,Record<string,number>>>({}),[pollVotes,setPollVotes]=useState<Record<string,string>>({});
  const listRef=useRef<HTMLDivElement>(null); const fileRef=useRef<HTMLInputElement>(null);

  const displayName=profile?.displayName||user.displayName||user.email?.split("@")[0]||"User";
  const currentServer=servers.find(s=>s.id===serverId); const currentChannel=channels.find(c=>c.id===channelId)||channels[0];
  const myRole=members.find(m=>m.uid===user.uid)?.role||"member"; const canManage=myRole==="owner"||myRole==="admin";
  const visibleMessages=useMemo(()=>search.trim()?messages.filter(m=>`${m.authorName||""} ${m.content}`.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR"))):messages,[messages,search]);

  useEffect(()=>onValue(ref(db,`users/${user.uid}/public`),s=>setProfile(s.val() as UserProfile|null)),[user.uid]);
  useEffect(()=>{
    return onValue(ref(db,`users/${user.uid}/servers`),snap=>{
      const ids=Object.keys(asMap<boolean>(snap.val()));
      Promise.all(ids.map(async id=>{const s=await get(ref(db,`servers/${id}`));return s.exists()?({...s.val(),id} as Server):null;})).then(v=>{const next=v.filter(Boolean) as Server[];setServers(next);setServerId(cur=>next.some(s=>s.id===cur)?cur:next[0]?.id||"");});
    });
  },[user.uid]);
  useEffect(()=>{
    if(!serverId){setChannels(fallbackChannels);setCategories(fallbackCats);setMembers([]);return;}
    const uc=onValue(ref(db,`channels/${serverId}`),s=>{const n=Object.entries(asMap<Channel>(s.val())).map(([id,v])=>({...v,id})).sort(byPosition);setChannels(n.length?n:fallbackChannels);setChannelId(cur=>n.some(c=>c.id===cur)?cur:(n.find(c=>c.type!=="voice")?.id||"general"));});
    const uk=onValue(ref(db,`categories/${serverId}`),s=>setCategories(Object.entries(asMap<Category>(s.val())).map(([id,v])=>({...v,id})).sort(byPosition)));
    const um=onValue(ref(db,`serverMembers/${serverId}`),s=>{const entries=Object.entries(asMap<{role?:string}>(s.val()));Promise.all(entries.map(async([uid,v])=>{const p=await get(ref(db,`users/${uid}/public`));return{uid,profile:p.exists()?p.val() as UserProfile:null,role:v.role||"member"};})).then(setMembers);});
    return()=>{uc();uk();um();};
  },[serverId]);
  useEffect(()=>{
    if(!serverId||!channelId||mode!=="server"||currentChannel?.type==="voice"){setMessages([]);return;}
    return onValue(ref(db,`messages/${serverId}/${channelId}`),s=>{const next=Object.entries(asMap<ChatMessage>(s.val())).map(([id,v])=>({...v,id,createdAt:timestamp(v.createdAt)})).sort((a,b)=>a.createdAt-b.createdAt).slice(-400);setMessages(next);});
  },[serverId,channelId,mode,currentChannel?.type]);
  useEffect(()=>{
    if(mode!=="dms"){setDmThreads([]);return;}
    return onValue(ref(db,`users/${user.uid}/dmThreads`),s=>{const ids=Object.keys(asMap<boolean>(s.val()));Promise.all(ids.map(async id=>{const t=await get(ref(db,`dmThreads/${id}`));if(!t.exists())return null;const thread=t.val() as DMThread;const other=Object.keys(thread.participants||{}).find(x=>x!==user.uid)||user.uid;const p=await get(ref(db,`users/${other}/public`));return {...thread,id,otherUid:other,profile:p.exists()?p.val() as UserProfile:null};})).then(v=>setDmThreads(v.filter(Boolean) as Array<DMThread&{id:string;otherUid:string;profile:UserProfile|null}>));});
  },[mode,user.uid]);
  useEffect(()=>{if(!selectedDm||mode!=="dms"){setDmMessages([]);return;}return onValue(ref(db,`dmMessages/${selectedDm}`),s=>setDmMessages(Object.entries(asMap<DMMessage>(s.val())).map(([id,v])=>({...v,id,createdAt:timestamp(v.createdAt)})).sort((a,b)=>a.createdAt-b.createdAt).slice(-400)));},[selectedDm,mode]);
  useEffect(()=>{return onValue(ref(db,`users/${user.uid}/friends`),s=>setFriends(Object.keys(asMap<boolean>(s.val()))))},[user.uid]);
  useEffect(()=>{return onValue(ref(db,`friendRequests/${user.uid}/incoming`),s=>setRequests(asMap(s.val()))},[user.uid]);
  useEffect(()=>{if(!threadId){setThreadMessages([]);return;}return onValue(ref(db,`threadMessages/${threadId}`),s=>setThreadMessages(Object.entries(asMap<ThreadMessage>(s.val())).map(([id,v])=>({...v,id,createdAt:timestamp(v.createdAt)})).sort((a,b)=>a.createdAt-b.createdAt)))},[threadId]);
  useEffect(()=>{if(listRef.current)listRef.current.scrollTop=listRef.current.scrollHeight},[messages,dmMessages,threadMessages]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(t)},[toast]);
  useEffect(()=>{if(!threadId)return;const q=onValue(ref(db,`threadMeta/${threadId}`),()=>undefined);return()=>q()},[threadId]);
  useEffect(()=>()=>{setCallChannel(null)},[]);

  async function sendMessage(e?:React.FormEvent){e?.preventDefault();const text=draft.trim();if(!text||!serverId||currentChannel?.type==="voice")return;setDraft("");
    try{
      if(text.startsWith("/github ")){const card=await fetchGithubRepo(text.slice(8));await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:"",createdAt:Date.now(),githubCard:card});setToast("GitHub kartı gönderildi");return;}
      if(text.startsWith("/music ")){const card=await fetchMusicCard(text.slice(7));await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:"",createdAt:Date.now(),musicCard:card});return;}
      await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:text,createdAt:Date.now(),replyTo:replyTo?{id:replyTo.id,authorName:replyTo.authorName,content:replyTo.content.slice(0,180)}:null});setReplyTo(null);
    }catch{setDraft(text);setToast("Mesaj gönderilemedi")}
  }
  async function editMessage(id:string){const text=editText.trim();if(!text)return;await update(ref(db,`messages/${serverId}/${channelId}/${id}`),{content:text,editedAt:Date.now()});setEditingId(null)}
  async function deleteMessage(id:string){await remove(ref(db,`messages/${serverId}/${channelId}/${id}`))}
  async function react(id:string,emoji:string){const r=ref(db,`reactions/${serverId}/${channelId}/${id}/${emoji}/${user.uid}`);const exists=await get(r);exists.exists()?await remove(r):await set(r,true)}
  async function createServer(){const n=serverName.trim();if(!n)return;setBusy();try{const r=push(ref(db,"servers"));const id=r.key!;const now=Date.now();await set(r,{name:n,ownerId:user.uid,createdAt:now});await set(ref(db,`serverMembers/${id}/${user.uid}`),{role:"owner",joinedAt:now});await set(ref(db,`users/${user.uid}/servers/${id}`),true);await set(push(ref(db,`channels/${id}`)),{name:"genel",type:"text",position:0,topic:"Genel sohbet"});await set(push(ref(db,`channels/${id}`)),{name:"sesli",type:"voice",position:1});setServerId(id);setMode("server");setCreateServerOpen(false);setServerName("");}catch{setToast("Sunucu oluşturulamadı")}finally{setBusy(false)}}
  async function createChannel(){const n=newChannelName.trim();if(!n||!serverId||!canManage)return;await set(push(ref(db,`channels/${serverId}`)),{name:n,type:"text",position:channels.length,topic:""});setNewChannelName("");setCreateChannelOpen(false)}
  async function addFriend(){const n=friendName.trim().toLowerCase();if(!n)return;const s=await get(ref(db,`usernameIndex/${n}`));if(!s.exists()){setToast("Kullanıcı bulunamadı");return}const uid=String(s.val());if(uid===user.uid){setToast("Kendini ekleyemezsin");return}await set(ref(db,`friendRequests/${uid}/incoming/${user.uid}`),{fromName:displayName,createdAt:Date.now()});await set(ref(db,`friendRequests/${user.uid}/outgoing/${uid}`),Date.now());setFriendName("");setToast("İstek gönderildi")}
  async function acceptFriend(uid:string){await set(ref(db,`friends/${user.uid}/${uid}`),true);await set(ref(db,`friends/${uid}/${user.uid}`),true);await remove(ref(db,`friendRequests/${user.uid}/incoming/${uid}`));await remove(ref(db,`friendRequests/${uid}/outgoing/${user.uid}`))}
  async function startDM(uid:string){const existing=dmThreads.find(t=>t.otherUid===uid);if(existing){setSelectedDm(existing.id);setMode("dms");return;}const r=push(ref(db,"dmThreads"));const id=r.key!;const participants={[user.uid]:true,[uid]:true};await set(r,{participants,createdAt:Date.now()});await set(ref(db,`users/${user.uid}/dmThreads/${id}`),true);await set(ref(db,`users/${uid}/dmThreads/${id}`),true);setSelectedDm(id);setMode("dms")}
  async function sendDM(e?:React.FormEvent){e?.preventDefault();const text=dmDraft.trim();if(!text||!selectedDm)return;setDmDraft("");await set(push(ref(db,`dmMessages/${selectedDm}`)),{authorId:user.uid,content:text,createdAt:Date.now()})}
  async function uploadFile(file:File){if(!serverId||currentChannel?.type==="voice")return;setBusy();try{const id=push(ref(db,`messages/${serverId}/${channelId}`)).key!;const data=file.type.startsWith("image/")?await fileToDataUrl(await compressImage(file)):await fileToDataUrl(file);const path=attachmentStoragePath(serverId,channelId,id,file.name);const token=await uploadAttachment(path,data,file.type||"application/octet-stream");const attachment:MessageAttachmentMeta={type:attachmentKind(file),name:file.name,size:file.size,storagePath:path,storageToken:token};await set(ref(db,`messages/${serverId}/${channelId}/${id}`),{serverId,channelId,authorId:user.uid,authorName:displayName,content:"",createdAt:Date.now(),attachment})}catch{setToast("Dosya yüklenemedi")}finally{setBusy(false);setPendingFile(null)}}
  async function searchGifAction(){if(!gifQuery.trim())return;try{setGifResults(await searchGifs(gifQuery))}catch{setToast("GIF araması başarısız")}}
  async function sendGif(url:string){await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:url,createdAt:Date.now()});setGifOpen(false)}
  async function postPoll(){const q=pollQuestion.trim(),options=pollOptions.map((x,i)=>({id:`o${i+1}`,text:x.trim(),votes:0})).filter(x=>x.text);if(!q||options.length<2)return;const p=push(ref(db,`polls/${serverId}/${channelId}`)),poll:Poll={id:p.key!,question:q,options,totalVotes:0,createdBy:user.uid};await set(p,poll);await set(push(ref(db,`messages/${serverId}/${channelId}`)),{serverId,channelId,authorId:user.uid,authorName:displayName,content:"",createdAt:Date.now(),poll});setPollOpen(false);setPollQuestion("");setPollOptions(["",""])}
  async function vote(pollId:string,optionId:string){await set(ref(db,`pollVotes/${pollId}/${user.uid}`),optionId);setPollVotes(v=>({...v,[pollId]:optionId}))}
  async function openThread(m:ChatMessage){const tm=m.threadId||push(ref(db,"threadMeta")).key!;if(!m.threadId){await set(ref(db,`threadMeta/${tm}`),{serverId,channelId,parentMessageId:m.id,createdAt:Date.now()});await update(ref(db,`messages/${serverId}/${channelId}/${m.id}`),{threadId:tm});}setThreadParent(m);setThreadId(tm)}
  async function sendThread(){const text=threadDraft.trim();if(!text||!threadId)return;setThreadDraft("");await set(push(ref(db,`threadMessages/${threadId}`)),{authorId:user.uid,content:text,createdAt:Date.now()})}
  async function createInvite(){if(!serverId)return;const code=Math.random().toString(36).slice(2,9).toUpperCase();await set(ref(db,`invites/${code}`),{serverId,createdBy:user.uid,createdAt:Date.now(),uses:0});setInviteCode(code);setInviteOpen(true)}
  async function joinInvite(){const code=joinCode.trim().toUpperCase();if(!code)return;const s=await get(ref(db,`invites/${code}`));if(!s.exists()){setToast("Davet bulunamadı");return}const data=s.val() as {serverId:string};const server=await get(ref(db,`servers/${data.serverId}`));if(!server.exists()){setToast("Sunucu bulunamadı");return}await set(ref(db,`serverMembers/${data.serverId}/${user.uid}`),{role:"member",joinedAt:Date.now()});await set(ref(db,`users/${user.uid}/servers/${data.serverId}`),true);setServerId(data.serverId);setMode("server");setJoinOpen(false);setJoinCode("")}
  async function copy(value:string){try{await navigator.clipboard.writeText(value);setToast("Kopyalandı")}catch{setToast(value)}}
  function setBusy(){setSending(true)} const [isSending,setSending]=useState(false); function setMode(next:"server"|"friends"|"dms"|"profile"){setModeState(next)} const [modeState,setModeState]=useState<"server"|"friends"|"dms"|"profile">("server"); const actualMode=modeState;

  if(!user)return null;
  return <main className="v15-shell">
    <SideNavigation user={user} profile={profile} displayName={displayName} servers={servers} serverId={serverId} setServerId={setServerId} mode={actualMode} setMode={setModeState} channels={channels} channelId={channelId} setChannelId={setChannelId} currentServer={currentServer} navOpen={navOpen} setNavOpen={setNavOpen} canManage={canManage} onCreateServer={()=>setCreateServerOpen(true)} onCreateChannel={()=>setCreateChannelOpen(true)} onCreateInvite={()=>void createInvite()} onJoinInvite={()=>setJoinOpen(true)}/>
    <section className="v15-main">
      <Topbar title={actualMode==="server"?(currentChannel?.name||"genel"):actualMode==="friends"?"Arkadaşlar":actualMode==="dms"?(dmThreads.find(x=>x.id===selectedDm)?.profile?.displayName||"Mesajlar"):"Profil"} subtitle={actualMode==="server"?currentChannel?.topic:undefined} onMenu={()=>setNavOpen(true)} right={actualMode==="server"&&<><div className="v15-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ara"/></div><button className="v15-icon-button" onClick={()=>setMemberPanel(v=>!v)}>☷</button></>}/>
      {actualMode==="server"&&currentChannel?.type==="voice" ? <div className="v15-voice-page"><VoiceRoom room={`signaling/${channelId}`} serverId={serverId} user={user}/></div> : actualMode==="server" ? <>
        <div className="v15-channel-body"><div className="v15-chat-body" ref={listRef}>
          <div className="v15-channel-intro"><span>#</span><h1>#{currentChannel?.name||"genel"}</h1><p>{currentChannel?.topic||"Kanalın başlangıcı."}</p></div>
          {visibleMessages.map(m=><MessageBubble key={m.id} message={m} mine={m.authorId===user.uid} editing={editingId===m.id} editText={editText} onEditText={setEditText} onSaveEdit={()=>void editMessage(m.id)} onCancelEdit={()=>setEditingId(null)} onReply={()=>setReplyTo(m)} onEdit={()=>{setEditingId(m.id);setEditText(m.content)}} onDelete={()=>void deleteMessage(m.id)} onReact={e=>void react(m.id,e)} onThread={()=>void openThread(m)} reactionCounts={reactionMap[m.id]||{}} pollVote={pollVotes[m.poll?.id||""]}/>)}</div>{memberPanel&&<MemberPanel members={members}/>}</div>
        {replyTo&&<div className="v15-reply-bar"><span><b>{replyTo.authorName||"User"}</b> yanıtlanıyor</span><button onClick={()=>setReplyTo(null)}>×</button></div>}
        <Composer draft={draft} setDraft={setDraft} onSubmit={sendMessage} onFile={f=>void uploadFile(f)} onGif={()=>setGifOpen(v=>!v)} onPoll={()=>setPollOpen(v=>!v)} disabled={isSending}/>
        {gifOpen&&<div className="v15-float-panel"><div className="v15-inline"><input value={gifQuery} onChange={e=>setGifQuery(e.target.value)} placeholder="GIF ara"/><button onClick={()=>void searchGifAction()}>Ara</button></div><div className="v15-gif-grid">{gifResults.map(url=><button key={url} onClick={()=>void sendGif(url)}><img src={url} alt="GIF"/></button>)}</div></div>}
        {pollOpen&&<PollComposer question={pollQuestion} setQuestion={setPollQuestion} options={pollOptions} setOptions={setPollOptions} onClose={()=>setPollOpen(false)} onCreate={()=>void postPoll()}/>}        
        {threadId&&<ThreadPanel parent={threadParent} messages={threadMessages} draft={threadDraft} setDraft={setThreadDraft} onSend={()=>void sendThread()} onClose={()=>{setThreadId(null);setThreadParent(null)}} currentUid={user.uid}/>}        
      </> : actualMode==="friends" ? <FriendsView friends={friends} requests={requests} name={displayName} friendName={friendName} setFriendName={setFriendName} onAdd={()=>void addFriend()} onAccept={uid=>void acceptFriend(uid)} onDM={uid=>void startDM(uid)}/> : actualMode==="dms" ? <DMView threads={dmThreads} selected={selectedDm} setSelected={setSelectedDm} messages={dmMessages} draft={dmDraft} setDraft={setDmDraft} onSend={()=>void sendDM()} currentUid={user.uid} onMenu={()=>setNavOpen(true)}/> : <ProfileView profile={profile} displayName={displayName} onEdit={()=>setProfileOpen(true)} />}
      {profileOpen&&<ProfileModal profile={profile} user={user} onClose={()=>setProfileOpen(false)} onSaved={p=>{setProfile(p);setProfileOpen(false)}}/>}
      {createServerOpen&&<CreateServerModal value={serverName} setValue={setServerName} busy={isSending} onClose={()=>setCreateServerOpen(false)} onCreate={()=>void createServer()}/>}      
      {createChannelOpen&&<CreateChannelModal value={newChannelName} setValue={setNewChannelName} onClose={()=>setCreateChannelOpen(false)} onCreate={()=>void createChannel()}/>}
      {inviteOpen&&<InviteModal code={inviteCode} onCopy={()=>void copy(inviteCode)} onClose={()=>setInviteOpen(false)}/>}      
      {joinOpen&&<JoinInviteModal value={joinCode} setValue={setJoinCode} onClose={()=>setJoinOpen(false)} onJoin={()=>void joinInvite()}/>}      
      {isSending&&<div className="v15-uploading">İşleniyor…</div>}{toast&&<div className="v15-toast">{toast}</div>}
    </section>
  </main>;
}

function Topbar({title,subtitle,onMenu,right}:{title:string;subtitle?:string;onMenu:()=>void;right?:React.ReactNode}){return <header className="v15-topbar"><button className="v15-menu" onClick={onMenu}>☰</button><div className="v15-top-title"><b>{title}</b>{subtitle&&<span>{subtitle}</span>}</div><div className="v15-top-actions">{right}</div></header>}

function SideNavigation({user,profile,displayName,servers,serverId,setServerId,mode,setMode,channels,channelId,setChannelId,currentServer,navOpen,setNavOpen,canManage,onCreateServer,onCreateChannel,onCreateInvite,onJoinInvite}:{user:User;profile:UserProfile|null;displayName:string;servers:Server[];serverId:string;setServerId:(x:string)=>void;mode:"server"|"friends"|"dms"|"profile";setMode:(x:"server"|"friends"|"dms"|"profile")=>void;channels:Channel[];channelId:string;setChannelId:(x:string)=>void;currentServer?:Server;navOpen:boolean;setNavOpen:(x:boolean)=>void;canManage:boolean;onCreateServer:()=>void;onCreateChannel:()=>void;onCreateInvite:()=>void;onJoinInvite:()=>void}){
 return <><aside className={`v15-sidebar ${navOpen?"open":""}`}><div className="v15-side-brand"><span className="v15-logo">A</span><div><b>AKAYROOM</b><small>V1.5</small></div><button className="v15-close-mobile" onClick={()=>setNavOpen(false)}>×</button></div><div className="v15-server-list"><button className={`v15-server-chip home ${mode==="profile"?"active":""}`} onClick={()=>{setMode("server");setNavOpen(false)}}>⌂</button>{servers.map(s=><button key={s.id} className={`v15-server-chip ${s.id===serverId&&mode==="server"?"active":""}`} onClick={()=>{setServerId(s.id);setMode("server");setNavOpen(false)}}>{s.iconUrl?<img src={s.iconUrl} alt=""/>:initials(s.name)}</button>)}<button className="v15-server-chip add" onClick={onCreateServer}>＋</button></div><div className="v15-nav-main"><div className="v15-server-heading"><span>SERVER</span><b>{currentServer?.name||"AkayRoom"}</b></div><button className={`v15-nav-action ${mode==="friends"?"active":""}`} onClick={()=>{setMode("friends");setNavOpen(false)}}>◉ Arkadaşlar</button><button className={`v15-nav-action ${mode==="dms"?"active":""}`} onClick={()=>{setMode("dms");setNavOpen(false)}}>✉ Mesajlar</button><div className="v15-nav-label">KANALLAR {canManage&&<button className="v15-mini-add" onClick={onCreateChannel}>＋</button>}</div>{channels.map(c=><button key={c.id} className={`v15-channel-row ${c.id===channelId&&mode==="server"?"active":""}`} onClick={()=>{setChannelId(c.id);setMode("server");setNavOpen(false)}}><span>{c.type==="voice"?"◉":c.type==="announcement"?"◈":"#"}</span>{c.name}</button>)}<div className="v15-nav-label">DAVET</div><div className="v15-invite-actions"><button className="v15-nav-action small" onClick={onCreateInvite}>＋ Davet oluştur</button><button className="v15-nav-action small" onClick={onJoinInvite}>⇢ Davetle katıl</button></div></div><button className={`v15-account ${mode==="profile"?"active":""}`} onClick={()=>{setMode("profile");setNavOpen(false)}}><div className="v15-avatar">{profile?.avatarUrl?<img src={profile.avatarUrl} alt=""/>:initials(displayName)}</div><div><b>{displayName}</b><span>online</span></div><span className="v15-more">⋯</span></button></aside>{navOpen&&<button className="v15-backdrop" onClick={()=>setNavOpen(false)} aria-label="Kapat"/>}</>;
}

function MessageBubble({message,mine,editing,editText,onEditText,onSaveEdit,onCancelEdit,onReply,onEdit,onDelete,onReact,onThread,reactionCounts,pollVote}:{message:ChatMessage;mine:boolean;editing:boolean;editText:string;onEditText:(x:string)=>void;onSaveEdit:()=>void;onCancelEdit:()=>void;onReply:()=>void;onEdit:()=>void;onDelete:()=>void;onReact:(x:string)=>void;onThread:()=>void;reactionCounts:Record<string,number>;pollVote?:string}){
 const isGif=typeof message.content==="string"&&/^https?:\/\//.test(message.content)&&(/giphy|media/i.test(message.content));
 const [pollChoice,setPollChoice]=useState(pollVote||"");
 return <article className={`v15-message ${mine?"mine":""}`}><div className="v15-avatar msg">{initials(message.authorName||"User")}</div><div className="v15-msg-main"><div className="v15-meta"><b>{message.authorName||"User"}</b><time>{fmtTime(message.createdAt)}</time>{message.editedAt&&<em>(düzenlendi)</em>}</div>{message.replyTo&&<div className="v15-quoted">↳ {message.replyTo.authorName}: {message.replyTo.content}</div>}{editing?<div className="v15-edit"><input value={editText} onChange={e=>onEditText(e.target.value)} autoFocus/><button onClick={onSaveEdit}>Kaydet</button><button onClick={onCancelEdit}>İptal</button></div>:isGif?<img className="v15-gif" src={message.content} alt="GIF"/>:<p>{message.content}</p>}{message.githubCard&&<GitHubCardView card={message.githubCard}/>} {message.musicCard&&<MusicCardView card={message.musicCard}/>} {message.attachment&&<AttachmentView attachment={message.attachment}/>} {message.poll&&<PollView poll={message.poll} selected={pollChoice} onVote={(id)=>setPollChoice(id)}/>}<div className="v15-msg-actions"><button onClick={onReply}>↩</button>{QUICK_REACTIONS.map(e=><button key={e} onClick={()=>onReact(e)}>{e}{reactionCounts[e]?<sup>{reactionCounts[e]}</sup>:null}</button>)}<button onClick={onThread}>⧉</button>{mine&&<><button onClick={onEdit}>✎</button><button onClick={onDelete}>⌫</button></>}</div></div></article>
}
function AttachmentView({attachment}:{attachment:MessageAttachmentMeta}){const [src,setSrc]=useState("");useEffect(()=>{if(attachment.storagePath&&attachment.storageToken)setSrc(storageDownloadUrl(attachment.storagePath,attachment.storageToken))},[attachment]);if(!src)return <div className="v15-attachment">{attachment.name} · {fmtSize(attachment.size)}</div>;if(attachment.type==="image")return <img className="v15-attachment-image" src={src} alt={attachment.name}/>;if(attachment.type==="video")return <video className="v15-attachment-media" src={src} controls/>;if(attachment.type==="audio")return <audio className="v15-attachment-audio" src={src} controls/>;return <a className="v15-file" href={src} download={attachment.name}>{attachment.name} · {fmtSize(attachment.size)}</a>}
function PollView({poll,selected,onVote}:{poll:Poll;selected:string;onVote:(id:string)=>void}){return <div className="v15-poll"><b>{poll.question}</b>{poll.options.map(o=><button key={o.id} className={selected===o.id?"selected":""} onClick={()=>onVote(o.id)}><span>{o.text}</span><small>{o.votes||0}</small></button>)}</div>}
function GitHubCardView({card}:{card:NonNullable<ChatMessage["githubCard"]>}){return <a className="v15-link-card" href={card.htmlUrl} target="_blank" rel="noreferrer"><strong>GitHub · {card.fullName}</strong><span>{card.description||""}</span><small>★ {card.stars.toLocaleString("tr-TR")} · forks {card.forks.toLocaleString("tr-TR")} · {card.language||"repo"}</small></a>}
function MusicCardView({card}:{card:NonNullable<ChatMessage["musicCard"]>}){return <div className="v15-music-card"><img src={card.artworkUrl} alt=""/><div><b>{card.trackName}</b><span>{card.artistName}</span><small>{card.collectionName}</small>{card.previewUrl&&<audio src={card.previewUrl} controls preload="none"/>}</div></div>}
function MemberPanel({members}:{members:Member[]}){return <aside className="v15-members"><span>ÜYELER · {members.length}</span>{members.map(m=><div className="v15-member" key={m.uid}><div className="v15-avatar">{m.profile?.avatarUrl?<img src={m.profile.avatarUrl} alt=""/>:initials(m.profile?.displayName||m.uid)}</div><div><b>{m.profile?.displayName||m.uid.slice(0,8)}</b><small>{m.role}</small></div></div>)}</aside>}
function Composer({draft,setDraft,onSubmit,onFile,onGif,onPoll,disabled}:{draft:string;setDraft:(x:string)=>void;onSubmit:(e:React.FormEvent)=>void;onFile:(f:File)=>void;onGif:()=>void;onPoll:()=>void;disabled:boolean}){const f=useRef<HTMLInputElement>(null);return <form className="v15-composer" onSubmit={onSubmit}><button type="button" className="v15-icon-button" onClick={()=>f.current?.click()}>＋</button><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Mesaj yaz…" disabled={disabled}/><button type="button" className="v15-chip-button" onClick={onGif}>GIF</button><button type="button" className="v15-chip-button" onClick={onPoll}>POLL</button><button type="submit" disabled={!draft.trim()||disabled}>➤</button><input ref={f} type="file" hidden accept="image/*,video/*,audio/*,.pdf,.zip,.txt,.doc,.docx,.json,.csv" onChange={e=>{const file=e.target.files?.[0];if(file)onFile(file);e.currentTarget.value=""}}/></form>}
function FriendsView({friends,requests,name,friendName,setFriendName,onAdd,onAccept,onDM}:{friends:string[];requests:Record<string,{fromName?:string;createdAt:number}>;name:string;friendName:string;setFriendName:(x:string)=>void;onAdd:()=>void;onAccept:(uid:string)=>void;onDM:(uid:string)=>void}){return <div className="v15-page"><section className="v15-card"><h1>Arkadaşlar</h1><div className="v15-inline"><input value={friendName} onChange={e=>setFriendName(e.target.value)} placeholder="kullanıcı adı"/><button onClick={onAdd}>İstek gönder</button></div></section>{Object.keys(requests).length>0&&<section className="v15-card"><h2>Gelen istekler</h2>{Object.entries(requests).map(([uid,r])=><div className="v15-list-row" key={uid}><span>{r.fromName||uid.slice(0,8)}</span><button onClick={()=>onAccept(uid)}>Kabul et</button></div>)}</section>}<section className="v15-card"><h2>Arkadaşlarım</h2>{friends.length?friends.map(uid=><div className="v15-list-row" key={uid}><span>@{uid.slice(0,10)}</span><button onClick={()=>onDM(uid)}>Mesaj</button></div>):<p className="muted">Henüz arkadaşın yok.</p>}</section></div>}
function DMView({threads,selected,setSelected,messages,draft,setDraft,onSend,currentUid,onMenu}:{threads:Array<DMThread&{id:string;otherUid:string;profile:UserProfile|null}>;selected:string|null;setSelected:(x:string|null)=>void;messages:DMMessage[];draft:string;setDraft:(x:string)=>void;onSend:()=>void;currentUid:string;onMenu:()=>void}){const active=threads.find(t=>t.id===selected);return <div className="v15-dm-layout"><div className="v15-dm-list">{threads.length?threads.map(t=><button key={t.id} className={selected===t.id?"active":""} onClick={()=>setSelected(t.id)}><span className="v15-avatar">{t.profile?.avatarUrl?<img src={t.profile.avatarUrl} alt=""/>:initials(t.profile?.displayName||t.otherUid)}</span><span><b>{t.profile?.displayName||t.otherUid.slice(0,8)}</b><small>@{t.profile?.username||"user"}</small></span></button>):<p className="muted">Henüz DM yok.</p>}</div><div className="v15-dm-chat"><div className="v15-dm-head"><button className="v15-menu" onClick={onMenu}>☰</button><b>{active?.profile?.displayName||"Bir konuşma seç"}</b></div>{selected?<><div className="v15-chat-body">{messages.map(m=><div className="v15-message" key={m.id}><div className="v15-avatar msg">{initials(m.authorId===currentUid?"Sen":active?.profile?.displayName||"User")}</div><div className="v15-msg-main"><div className="v15-meta"><b>{m.authorId===currentUid?"Sen":active?.profile?.displayName||"User"}</b><time>{fmtTime(m.createdAt)}</time></div><p>{m.content}</p></div></div>)}</div><form className="v15-composer" onSubmit={e=>{e.preventDefault();onSend()}}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Mesaj yaz…"/><button disabled={!draft.trim()}>➤</button></form></>:<div className="v15-empty-big">Bir konuşma seç.</div>}</div></div>}
function ProfileView({profile,displayName,onEdit}:{profile:UserProfile|null;displayName:string;onEdit:()=>void}){return <div className="v15-page"><section className="v15-profile"><div className="v15-banner" style={{backgroundImage:profile?.bannerUrl?`url(${profile.bannerUrl})`:undefined,backgroundColor:profile?.bannerColor||"#171b27"}}/><div className="v15-profile-head"><div className="v15-big-avatar">{profile?.avatarUrl?<img src={profile.avatarUrl} alt=""/>:initials(displayName)}</div><div><h1>{displayName}</h1><p>@{profile?.username||"user"}</p>{profile?.title&&<span className="v15-pill">{profile.title}</span>}</div></div>{profile?.customStatus&&<div className="v15-status">{profile.customStatusEmoji} {profile.customStatus}</div>}{profile?.bio&&<p className="v15-bio">{profile.bio}</p>}</section><button className="v15-primary" onClick={onEdit}>Profili düzenle</button></div>}
function ThreadPanel({parent,messages,draft,setDraft,onSend,onClose,currentUid}:{parent:ChatMessage|null;messages:ThreadMessage[];draft:string;setDraft:(x:string)=>void;onSend:()=>void;onClose:()=>void;currentUid:string}){return <div className="v15-thread-panel"><div className="v15-thread-head"><div><b>Yanıt dizisi</b><small>{parent?.authorName||"Mesaj"}</small></div><button onClick={onClose}>×</button></div><div className="v15-thread-body">{parent&&<div className="v15-thread-parent"><b>{parent.authorName}</b><p>{parent.content}</p></div>}{messages.map(m=><div className="v15-thread-message" key={m.id}><b>{m.authorId===currentUid?"Sen":m.authorId.slice(0,8)}</b><p>{m.content}</p><time>{fmtTime(m.createdAt)}</time></div>)}</div><form className="v15-thread-composer" onSubmit={e=>{e.preventDefault();onSend()}}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Yanıta yaz…"/><button disabled={!draft.trim()}>➤</button></form></div>}
function PollComposer({question,setQuestion,options,setOptions,onClose,onCreate}:{question:string;setQuestion:(x:string)=>void;options:string[];setOptions:(x:string[])=>void;onClose:()=>void;onCreate:()=>void}){return <div className="v15-float-panel"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Anket sorusu"/>{options.map((o,i)=><input key={i} value={o} onChange={e=>setOptions(options.map((x,j)=>j===i?e.target.value:x))} placeholder={`Seçenek ${i+1}`}/>)}<div className="v15-inline"><button type="button" onClick={()=>setOptions([...options,""])}>＋</button><button type="button" onClick={onClose}>İptal</button><button type="button" className="v15-primary" onClick={onCreate}>Oluştur</button></div></div>}
function CreateServerModal({value,setValue,busy,onClose,onCreate}:{value:string;setValue:(x:string)=>void;busy:boolean;onClose:()=>void;onCreate:()=>void}){return <Modal title="Yeni sunucu" onClose={onClose}><p className="muted">Yeni bir topluluk oluştur.</p><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Sunucu adı" autoFocus/><div className="v15-modal-actions"><button onClick={onClose}>İptal</button><button className="v15-primary" disabled={!value.trim()||busy} onClick={onCreate}>Oluştur</button></div></Modal>}
function CreateChannelModal({value,setValue,onClose,onCreate}:{value:string;setValue:(x:string)=>void;onClose:()=>void;onCreate:()=>void}){return <Modal title="Yeni kanal" onClose={onClose}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="kanal adı" autoFocus/><div className="v15-modal-actions"><button onClick={onClose}>İptal</button><button className="v15-primary" disabled={!value.trim()} onClick={onCreate}>Oluştur</button></div></Modal>}
function InviteModal({code,onCopy,onClose}:{code:string;onCopy:()=>void;onClose:()=>void}){return <Modal title="Sunucu daveti" onClose={onClose}><div className="v15-invite-code">{code}</div><div className="v15-modal-actions"><button onClick={onCopy}>Kopyala</button><button className="v15-primary" onClick={onClose}>Tamam</button></div></Modal>}
function JoinInviteModal({value,setValue,onClose,onJoin}:{value:string;setValue:(x:string)=>void;onClose:()=>void;onJoin:()=>void}){return <Modal title="Davetle katıl" onClose={onClose}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="DAVETKODU" autoFocus/><div className="v15-modal-actions"><button onClick={onClose}>İptal</button><button className="v15-primary" disabled={!value.trim()} onClick={onJoin}>Katıl</button></div></Modal>}
function ProfileModal({profile,user,onClose,onSaved}:{profile:UserProfile|null;user:User;onClose:()=>void;onSaved:(p:UserProfile)=>void}){const [name,setName]=useState(profile?.displayName||"");const [bio,setBio]=useState(profile?.bio||"");const [status,setStatus]=useState(profile?.customStatus||"");return <Modal title="Profil ayarları" onClose={onClose}><label>GÖRÜNEN AD<input value={name} onChange={e=>setName(e.target.value)}/></label><label>BIO<textarea value={bio} onChange={e=>setBio(e.target.value)} rows={4}/></label><label>DURUM<input value={status} onChange={e=>setStatus(e.target.value)} placeholder="Kod yazıyor…"/></label><div className="v15-modal-actions"><button onClick={onClose}>İptal</button><button className="v15-primary" onClick={async()=>{const next={...(profile||{}),username:profile?.username||user.email?.split("@")[0]||"user",usernameLower:profile?.usernameLower||user.email?.split("@")[0]?.toLowerCase()||"user",displayName:name.trim()||"User",bio,customStatus:status,createdAt:profile?.createdAt||Date.now()};await update(ref(db,`users/${user.uid}/public`),next);onSaved(next as UserProfile)}}>Kaydet</button></div></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="v15-modal-wrap"><div className="v15-modal"><div className="v15-modal-head"><b>{title}</b><button onClick={onClose}>×</button></div>{children}</div></div>}
